input {
  file {
    # This path is relative to where the folder is mounted in Docker
    path => "/usr/share/logstash/pipeline/logs/sample.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sample-logs"
  }
  stdout { codec => rubydebug }
}
